In [4]:
import numpy as np
print(np.__version__)   # version check

1.21.5


In [14]:
llist = [ 1,2,3,4,5,6]
numpy_array = np.array(llist)
print(type(numpy_array))
print(numpy_array)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [13]:
#Arithematic operations of numpy
print(numpy_array * 2)
print(numpy_array + 2)
print(numpy_array - 2)
print(numpy_array / 2)
print(numpy_array % 2)
print(numpy_array // 2)


[ 2  4  6  8 10 12]
[3 4 5 6 7 8]
[-1  0  1  2  3  4]
[0.5 1.  1.5 2.  2.5 3. ]
[1 0 1 0 1 0]
[0 1 1 2 2 3]


In [36]:
#Shape of Array
import numpy as np
a = np.array([[1,2],[2,3],[3,4],[4,4]])   #data must be symmetric !! 
print(a.shape)
print(a.dtype,"  --> bit, dataType and dataStorage")
b = np.array([1.1,2.0,3.2])
print(b.dtype,"--> bit, dataType and dataStorage")
b = np.array([[[1,2,3],[2,3,4]]]) # ----> rows and then column
print(b.shape,"---> Row, Column, and elements")
 #4 dimension w.r.t ---> 5 --> parallel tasks.

(4, 2)
int32   --> bit, dataType and dataStorage
float64 --> bit, dataType and dataStorage
(1, 2, 3) ---> Row, Column, and elements


In [12]:
# NULL and UNIT matrix not math matrix
import numpy as np
b= np.zeros((3,3))
c= np.ones((2,2))
print(b,"\n\n",c)

#reshaping a matrix --> ( changing size of matrix ) 
A = np.array([[1,2,3,4],[4,3,2,1]])
print('\n',A,"This is A matrix")
print(A.reshape(2,4)," This is 2/3 matrix") # Factos of m*n = number of times it can be shaped.
print(A.reshape(8,1)," This is 2/1 matrix")



#Flatten meaning change it into one dimensional
A.flatten()
print(A,"Flatten Converted")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

 [[1. 1.]
 [1. 1.]]

 [[1 2 3 4]
 [4 3 2 1]] This is A matrix
[[1 2 3 4]
 [4 3 2 1]]  This is 2/3 matrix
[[1]
 [2]
 [3]
 [4]
 [4]
 [3]
 [2]
 [1]]  This is 2/1 matrix
[[1 2 3 4]
 [4 3 2 1]] Flatten Converted
Horizontal Append: 
 [[1 2 4 5]
 [1 2 4 5]
 [3 4 3 6]]
1


In [48]:
#hstack() for appending data horizontally
import numpy as np
a = np.array([[1,2],[1,2],[3,4]])
b = np.array([[4,5],[4,5],[3,6]])
print('Horizontal Append: \n', np.hstack((a, b)))
print('Horizontal Append: \n', np.vstack((a, b)))    #order of a and b matters !! 
print('Horizontal Append: \n', np.hstack((b, a)))
print('Horizontal Append: \n', np.vstack((b, a)))  
C = np.hstack((a,b))
print(C.flatten(),"This is flattern of C ")

#Generating random number

# Random numbers between [0,1) of shape 2,2 #Normal distribution with mean=0 and varience=1 of shape 2,2
print(np.random.rand(2,2),"This is randowm number of shape 2/2")

# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]),"This is random integer number of size 2/2")

# One random number between [0,1)
print(np.random.random())

print(np.random.randint(10.5, 20.2, size=[10,10]),"This is random integer number of size 10/10")

Horizontal Append: 
 [[1 2 4 5]
 [1 2 4 5]
 [3 4 3 6]]
Horizontal Append: 
 [[1 2]
 [1 2]
 [3 4]
 [4 5]
 [4 5]
 [3 6]]
Horizontal Append: 
 [[4 5 1 2]
 [4 5 1 2]
 [3 6 3 4]]
Horizontal Append: 
 [[4 5]
 [4 5]
 [3 6]
 [1 2]
 [1 2]
 [3 4]]
[1 2 4 5 1 2 4 5 3 4 3 6] This is flattern of C 
[[0.95059824 0.74958292]
 [0.53945868 0.5935089 ]] This is randowm number of shape 2/2
[[1 6]
 [9 9]] This is random integer number of size 2/2
0.2191784878428945
[[19 16 16 15 14 15 16 10 13 13]
 [17 18 11 19 11 14 14 10 11 12]
 [15 18 19 14 12 19 14 11 11 12]
 [12 13 17 11 12 13 16 14 10 18]
 [17 12 18 10 19 17 17 14 12 17]
 [15 13 14 18 13 18 15 19 19 14]
 [13 11 14 17 11 10 19 13 14 11]
 [18 16 13 16 19 16 15 19 10 11]
 [12 16 16 18 19 12 17 12 18 10]
 [17 13 14 17 11 13 10 16 18 18]] This is random integer number of size 10/10


In [1]:
# permutation and combination concept
print(np.random.choice(['b','i','k','r','a','m'],size=6))

print(np.random.choice(['b','i','k','r','a','m'],size=6, p = [0.1,0.2,0.3,0.1,0.1,0.2])) # p means probabily of element of array


#Statistical function
import numpy as np
b = np.random.randint(10, 20, size=[20,20])
c = b.flatten()
print(c)
print(np.max(c))
print(np.min(c))
print(np.mean(c),np.median(c),np.std(c))

import scipy.linalg as slin                   # Scientific python.linear algebra  
print("Printing determinant of a matrix",slin.det(b))
# print("Printing inverse of a matrix",slin.inv(b))
print(np.trace(b))  # Sum of diagonal elements of a matrix

NameError: name 'np' is not defined

In [8]:
import numpy as np
a=np.matrix([[ 3, -5, 8],
[-1, 2, 3],
[-5, -6, 2]])
b=np.matrix([[ 3],[ 4],[-1]])
print(a*b)

[[-19]
 [  2]
 [-41]]
