In [4]:
import numpy as np
print(np.__version__)   # version check

1.21.5


In [14]:
llist = [ 1,2,3,4,5,6]
numpy_array = np.array(llist)
print(type(numpy_array))
print(numpy_array)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [13]:
#Arithematic operations of numpy
print(numpy_array * 2)
print(numpy_array + 2)
print(numpy_array - 2)
print(numpy_array / 2)
print(numpy_array % 2)
print(numpy_array // 2)


[ 2  4  6  8 10 12]
[3 4 5 6 7 8]
[-1  0  1  2  3  4]
[0.5 1.  1.5 2.  2.5 3. ]
[1 0 1 0 1 0]
[0 1 1 2 2 3]


In [36]:
#Shape of Array
import numpy as np
a = np.array([[1,2],[2,3],[3,4],[4,4]])   #data must be symmetric !! 
print(a.shape)
print(a.dtype,"  --> bit, dataType and dataStorage")
b = np.array([1.1,2.0,3.2])
print(b.dtype,"--> bit, dataType and dataStorage")
b = np.array([[[1,2,3],[2,3,4]]]) # ----> rows and then column
print(b.shape,"---> Row, Column, and elements")
 #4 dimension w.r.t ---> 5 --> parallel tasks.

(4, 2)
int32   --> bit, dataType and dataStorage
float64 --> bit, dataType and dataStorage
(1, 2, 3) ---> Row, Column, and elements


In [64]:
# NULL and UNIT matrix not math matrix
import numpy as np
b= np.zeros((3,3))
c= np.ones((2,2))
print(b,"\n\n",c)

#reshaping a matrix --> ( changing size of matrix ) 
A = np.array([[1,2,3,4],[4,3,2,1]])
print('\n',A,"This is A matrix")
print(A.reshape(2,4)," This is 2/3 matrix") # Factos of m*n = number of times it can be shaped.
print(A.reshape(8,1)," This is 2/1 matrix")



#Flatten meaning change it into one dimensional
A.flatten()
print(A,"Flatten Converted")



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

 [[1. 1.]
 [1. 1.]]

 [[1 2 3 4]
 [4 3 2 1]] This is A matrix
[[1 2 3 4]
 [4 3 2 1]]  This is 2/3 matrix
[[1]
 [2]
 [3]
 [4]
 [4]
 [3]
 [2]
 [1]]  This is 2/1 matrix
[[1 2 3 4]
 [4 3 2 1]] Flatten Converted
